CREATE TABLE IF NOT EXISTS RUTAS_GUARDADAS (
  USUARIO_ID BIGINT NOT NULL,
  RUTA_ID BIGINT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USUARIO_ID, RUTA_ID),
  CONSTRAINT FK_RG_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES usuario(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RG_RUTA FOREIGN KEY (RUTA_ID) REFERENCES ruta(id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
